# Generated by Django 4.2 on 2023-09-01 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatapp", "0007_alter_room_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
