# Generated by Django 4.2 on 2023-09-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0008_alter_room_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_password_set",
            field=models.BooleanField(default=False),
        ),
    ]
