# Generated by Django 4.2 on 2023-09-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0009_room_is_password_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="is_password_set",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
