# Generated by Django 4.2 on 2023-09-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0011_privateroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(default=1, upload_to="room_images/"),
            preserve_default=False,
        ),
    ]
