# Generated by Django 4.2 on 2023-09-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0012_room_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(max_length=40, null=True),
        ),
    ]
