# Generated by Django 4.2 on 2023-09-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0013_alter_room_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(max_length=30, null=True),
        ),
    ]
