# Generated by Django 4.2 on 2023-09-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0014_alter_room_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
