# Generated by Django 4.2 on 2023-04-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profileapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="introduction",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
