# Generated by Django 4.2 on 2023-05-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commentapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
    ]
