# Generated by Django 4.2 on 2023-05-25 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedapp", "0003_remove_feed_like"),
        ("likeapp", "0002_alter_likes_feed_alter_likes_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likes",
            name="feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="feedapp.feed",
            ),
        ),
        migrations.AlterField(
            model_name="likes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
