# Generated by Django 4.2 on 2023-05-23 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="like",
            field=models.ManyToManyField(
                related_name="like_feed", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="like_cnt",
            field=models.IntegerField(default=0),
        ),
    ]
